### ISSUE TITLE
my switch crash when docked error 2345-0021

### ISSUE THREAD

**Issue by veda95110** [Cpasjuste/psnes#15]
Hi, i have an issue with Psnes and that doesn't happen in pfba:
The emulator play perfect when the switch is undocked (in my hands) but as soon i dock the switch, it crash with error screen 2345-0021, sometimes after 10 seconds and sometimes immediatly.
I use sx os 1.3 with a samsung 128gb sd formated in exfat and hbmenu 2.0 and no auto rcm.
If you have an idea that would be great, thanks

**Comment by 18Phoenix** [comment]
Hi there, same here.
I tried pSNES the first time. It works fine in handheld-mode, but always crashes in TV mode after starting a game or switching from handheld to TV.
5.1.0 Switch + SX OS 1.5 + pSNES 1.5
So the emu is useless for all TV users.
I hope to set this problem to first priority and for a fast fix.
Thanks :D

**Comment by gonzogonzales** [comment]
This issue schoud be fixed with the 1.6 Version.

**Comment by Cpasjuste** [comment]
Fixed since 1.6
