### ISSUE TITLE
Saves don't work properly

### ISSUE THREAD

**Issue by Frydie** [Cpasjuste/psnes#19]
The saves work kinda strange, the first time you save in a game they work properly and the next time you boot that game up the save file is there but, every save file you do after the first one won't work.
The save state feature doesn't work well either, sometimes they get corrupted.

I tried to run the homebrew via the hombrew launcher and also with the one incorporated in sx os 1.4, either way the issue remains.

**Comment by Cpasjuste** [comment]
Hi, i just tested the save functions etc and all seems to work correctly. I know there are some problem when using an exFAT formated sdcard. Is it what's you are using ?

**Comment by mercury501** [comment]
Can confirm on exfat SD sometimes the save state from a couple of seconds before doesn't load, it says it's not a snes9x format savestate. Don't know about normal saves, can test tough

**Comment by Cpasjuste** [comment]
Solution: switch to FAT formated sdcard ,:/
