### ISSUE TITLE
Issues found through testing this morning.

### ISSUE THREAD

**Issue by es0501** [Cpasjuste/psnes#2]
The emulator doesn't work on 5.1.0 when using Team Xecuter's Payload.bin, worked fine once I switched back to the original payload.bin however. Trying to use Xecuter causes a crash when loading a rom.

Sleep mode is a no go and drastically drops fps

Home button is a no go and effectively closes the emulator, I don't think anything can really be done about this one though but I figured I'd throw it here anyway.

The Switch might crash with an error screen if left idle and allowed to go into sleep.

**Comment by gnmmarechal** [comment]
The issue with SX OS isn't unique to this emulator. Other emulators, including VBANext, refuse to work under SX OS, or have performance and sound issues.

**Comment by Cpasjuste** [comment]
Hi,
I'll take a look but i'm not sure this is something we can fix. Probably only TX can.

**Comment by Cpasjuste** [comment]
There's really nothing i can do, we must wait for TX.
