### ISSUE TITLE
Kirby's Dream Land 3 glitchy water

### ISSUE THREAD

**Issue by SexySpai** [Cpasjuste/psnes#4]
Hi. I've stumbled upon a very odd glitch involving water in Kirby's Dream Land 3. Normally, water should be transparent and you should see whats in it, but in psnes, the water is just solid gray and I can't see anything in it. It probably involves the sprite layer but i'm not sure. Is there a way to fix this?

![2018062016081700-db1426d1dfd034027cecde9c2dd914b8](https://user-images.githubusercontent.com/40442784/41685977-646d36de-74b0-11e8-8dc2-7d928d4e0a39.jpg)
![2018062016150900-db1426d1dfd034027cecde9c2dd914b8](https://user-images.githubusercontent.com/40442784/41685983-68eda036-74b0-11e8-9114-17e7223b372c.jpg)

oh and its v1.1 beta

**Comment by Cpasjuste** [comment]
Hi @SexySpai, could you share a save state (located in "saves/Kirby's Dream Land 3 (USA)0.sav" for example) where there is some water ?

**Comment by SexySpai** [comment]
Ok

**Comment by SexySpai** [comment]
I gotta do it a bit later though

**Comment by SexySpai** [comment]
[kdl3 save.zip](https://github.com/Cpasjuste/psnes/files/2124747/kdl3.save.zip)

**Comment by Cpasjuste** [comment]
Many thanks for your time. I'll take a look tonight.

**Comment by Cpasjuste** [comment]
Thanks again. It's fixed since 55d0ccaa21b217236fbabc82984a9f2b53f48e98  :)
Will be working in next release (maybe tomorrow, or a few days at worst).

**Comment by SexySpai** [comment]
Nice
