### ISSUE TITLE
Loading Issue.

### ISSUE THREAD

**Issue by jjlink05** [Cpasjuste/psnes#6]
I am on firmware 5.1.0, using PSNES 1.1 beta and the Emulator Runs fine, but when I open a rom it hangs.
I have to hold the power button until the switch turns off. Any Help?

Do I need a SNES Bios for the emulator?

**Comment by jjlink05** [comment]
Okay you can close this thread it's an issue with 5.1.0 and the SX OS as I read in the other issue.

**Comment by Cpasjuste** [comment]
There's really nothing i can do, we must wait for TX.
