### ISSUE TITLE
Saving acting strange

### ISSUE THREAD

**Issue by newbytime7** [Cpasjuste/psnes#7]
Saves from 1.1 beta do not work with 1.2. Also, when I created a new save from 1.2 and then delete it, the game still sees the save... not sure whats happening here.

**Comment by Cpasjuste** [comment]
Hi, it works fine here, are you sure you don't have an sdcard problem ? Also, exFAT sdcard have a lot of problems with homebrews.

**Comment by newbytime7** [comment]
I will reformat to fat32 and retry

**Comment by newbytime7** [comment]
Still not recognizing save after reformat to FAT32. Did figure out that deleting the sram got rid of the "phantom save" but the oops file still isn't being seen.

**Comment by newbytime7** [comment]
Ok! After much more testing, I have figured some things out. It seems that the .oops file in /switch/psnes/saves really doesn't do anything. When going from 1.1 beta to 1.2, I only backed up the save file and deleted the sram folder which contains a .srm. In that case the save did not load. In my recent testing, I tried loading the .oops file on a computer with snes9x 1.55 to no avail. Then when updating to 1.3 on the switch, I saved both the sram and the saves. This resulted in the saves being there. I did also notice that everytime I deleted the .srm and tried to start the game, the app crashed and I had to restart my switch. If you wouldn't mind testing on your end to see if you get similar results that would be awesome. Or if this is known and I'm just being dumb you can let me know that too.

**Comment by aforty** [comment]
I can't get my games to save. Running 1.5 and SD card formatted with exfat.

**Comment by Cpasjuste** [comment]
Solution: switch to FAT formated sdcard :/
